version: '2'
services:
  db:
    image: mysql:5.7
    container_name: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD="password"
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
  app:
    build: .
    container_name: "node_app"
    volumes:
      - ./app:/usr/src/ahk
    ports:
      - 80:8080
    links:
      - db
